### ISSUE TITLE
App flow updates

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/evernym-tc-wallet#26]
Currently, on app launch, we validate the user's passcode / FaceID and then go right into the wallet itself.

Now we want to change navigation a bit:

* In the left menu, we'll add `Wallet` and `Topcoder`
* On initial login we'll go right into the app - initial view should just be a basic tutorial
* When the user selects `Wallet`, *then* we will initialise the wallet, if not already done
* When the user selects `Topcoder` they will get additional options for `Login` and `Challenges`
  * When the user selects `Login`, we'll log them in on the TC site
  * When the user selects `Challenges` and aren't logged in, they'll see all challenges 
    *  If we can design a similar filter mechanism to the community app, that would help
  * When the user selects `Challenges` and they're logged in, they'll see their current challenges

### Current storyboards

* https://marvelapp.com/prototype/5ig7b8c
* https://www.dropbox.com/s/08omi9yiwp0shek/Deliverables-20201230T033304Z-001.zip?dl=1

**Comment by fajarmln** [comment]
For information, design updates is on progress and we will get the initial design on this weekend

**Comment by fajarmln** [comment]
Design is updated:

- Marvel Link: https://marvelapp.com/prototype/5ig7b8c

- Storyboard Updates: https://drive.google.com/drive/folders/1HJXDbA8vG5c5Qp7c11gpDGJ7bMr3lXIk?usp=sharing

**Comment by jmgasper** [comment]
@fajarmln - This looks really good, thanks.  Feel free to close this out on your end so yourself and the designer get paid!
